<%@ page language="java" contentType="text/html; charset=utf-8"
	pageEncoding="utf-8"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<title>Insert title here</title>
<link href="../../css/bootstrap.min.css" rel="stylesheet">
<link href="../../css/dashboard.css" rel="stylesheet">
</head>
<body>
	<h2>钱包表</h2>
	<table class="table table-striped">
		<thead>
			<tr>
				<th>id</th>
				<th>Header</th>
				<th>Header</th>
				<th>Header</th>
				<th>Header</th>
			</tr>
		</thead>

		<tbody>
			<tr>
				<td>1,001</td>
				<td>Lorem</td>
				<td>ipsum</td>
				<td>dolor</td>
				<td>sit</td>
			</tr>
			<tr>
				<td>1,002</td>
				<td>amet</td>
				<td>consectetur</td>
				<td>adipiscing</td>
				<td>elit</td>
			</tr>
			<tr>
				<td>1,003</td>
				<td>Integer</td>
				<td>nec</td>
				<td>odio</td>
				<td>Praesent</td>
			</tr>
			<tr>
				<td>1,003</td>
				<td>libero</td>
				<td>Sed</td>
				<td>cursus</td>
				<td>ante</td>
			</tr>
			<tr>
				<td>1,004</td>
				<td>dapibus</td>
				<td>diam</td>
				<td>Sed</td>
				<td>nisi</td>
			</tr>
			<tr>
				<td>1,005</td>
				<td>Nulla</td>
				<td>quis</td>
				<td>sem</td>
				<td>at</td>
			</tr>
			<tr>
				<td>1,006</td>
				<td>nibh</td>
				<td>elementum</td>
				<td>imperdiet</td>
				<td>Duis</td>
			</tr>
			<tr>
				<td>1,007</td>
				<td>sagittis</td>
				<td>ipsum</td>
				<td>Praesent</td>
				<td>mauris</td>
			</tr>
			<tr>
				<td>1,008</td>
				<td>Fusce</td>
				<td>nec</td>
				<td>tellus</td>
				<td>sed</td>
			</tr>
			<tr>
				<td>1,009</td>
				<td>augue</td>
				<td>semper</td>
				<td>porta</td>
				<td>Mauris</td>
			</tr>
			<tr>
				<td>1,010</td>
				<td>massa</td>
				<td>Vestibulum</td>
				<td>lacinia</td>
				<td>arcu</td>
			</tr>
			<tr>
				<td>1,011</td>
				<td>eget</td>
				<td>nulla</td>
				<td>Class</td>
				<td>aptent</td>
			</tr>
			<tr>
				<td>1,012</td>
				<td>taciti</td>
				<td>sociosqu</td>
				<td>ad</td>
				<td>litora</td>
			</tr>
			<tr>
				<td>1,013</td>
				<td>torquent</td>
				<td>per</td>
				<td>conubia</td>
				<td>nostra</td>
			</tr>
			<tr>
				<td>1,014</td>
				<td>per</td>
				<td>inceptos</td>
				<td>himenaeos</td>
				<td>Curabitur</td>
			</tr>
			<tr>
				<td>1,015</td>
				<td>sodales</td>
				<td>ligula</td>
				<td>in</td>
				<td>libero</td>
			</tr>
		</tbody>
	</table>
	</div>
</body>
</html>
